#!/usr/bin/perl -w

use strict;
use warnings;
use feature qw( switch );
no if $] ge '5.018', warnings => 'experimental::smartmatch';

use Term::ANSIColor;
use Term::ReadKey;
use Data::Dumper;
use DBI;
use Date::Calc qw( Today_and_Now );

use lib '/root/local-admin-scripts';
use Monitors;

my $action = $ARGV[0];

die colored("Need an action! \n", "bold red") if ((!defined($action)) or ($action eq ''));

my ($host_id, $date_str);

my $time = time();
my ($y,$m,$d,$h,$M,$s) = Today_and_Now($time);
$date_str = "$y/$d/$m $h:$M:$s";

$host_id = &get_host_id;

given ($action) {
	when (/memory/) {
		my ($mem,$swap,$total) = Monitors->get_meminfo;
		#print Dumper($mem);
		#print Dumper($swap);
		#print Dumper($total);
		my $isql = "INSERT INTO memstats (host_id,total_memory,free_memory,total_swap,free_swap,date_entered) VALUES ('$host_id','$mem->{'total'}','$mem->{'free'}','$swap->{'total'}','$swap->{'free'}','$date_str')";
		print "iSQL:  $isql \n";
	}
	default {
		print "No or unrecognized action specified. \n";
	}
}

sub get_host_id {
	my $h = '';
	print "Enter database password: ";
	ReadMode('noecho');
	chomp(my $pass = <STDIN>);
	ReadMode(0);
	print "\n";
	my $hn = Monitors->get_binary('hostname');
	my $hostname = qx($hn -f);
	chomp($hostname);
	print colored("$hostname \n", "bold magenta");
	my $dsn = "dbi:mysql:database=sysstats;host=salt.dataking.us";
	my $db = DBI->connect($dsn, 'root', $pass) or die colored($DBI::errstr,"\n", "bold red");
	my $st = $db->prepare("SELECT id FROM systems where hostname='$hostname'") 
		or die colored($DBI::errstr."\n", "bold red");
	my $rtv = $st->execute or die colored($DBI::errstr."\n", "bold red");
	while (my @row = $st->fetchrow_array) { $h = $row[0]; last; }
	$st->finish or die colored($DBI::errstr."\n", "bold red");
	$db->disconnect or die colored($DBI::errstr."\n", "bold red");
	if ((defined($h)) and ($h ne "")) {
		return $h;
	} else { die colored("Couldn't get host id. \n", "bold red"); }
}
