#!/usr/bin/perl -w

use strict;
# this is disabled to give better cross-platform compatibility without excessive warnings from
# the perl interpreter.  
use warnings;
use feature qw( switch );
#print "PERLVER: $] \n";
use 5.010;
# perls prior to 5.18 don't consider the smartmatch feature "experimental, so it is a compile-time
# error.  The only option seems to be disabling warnings.
no warnings "experimental::smartmatch";

use Term::ANSIColor;
use Data::Dumper;
use Getopt::Long qw( :config no_ignore_case bundling );

use YAML qw( LoadFile );
use MIME::Lite;

use LASObjects::Sensor;

my ($help,$verbose,$config);
$verbose = 0;
GetOptions(
	'h|help'		=>	\$help,
	'v|verbose+'	=>	\$verbose,
	'c|config=s'	=>	\$config,
);

my ($free, $df, $sensors);
my %from_bool	= ('true'=>1, 'false'=>0);
my %to_bool	= (1=>'true', 0=>'false');
my %Sensor = (
	'id'		=>	'',
	'bus'		=>	'',
	'adapter'	=>	'',
	'node'		=>	'',
	'sensor'	=>	'',
	'temp'		=>	'',
);
my %HashOfSensors;

&get_binaries;

&usage if ($help);

if (scalar(@ARGV) > 1) {
	print colored("Only one action verb expected.  Got ".scalar(@ARGV).".\n", "bold red");
	&usage;
}

if (scalar(@ARGV) == 0) {
	print colored("At least one action verb expected.  Got 0. \n", "bold red");
	&usage;
}

if ((!defined($config)) or ($config eq "")) {
	print colored("You must specify a config file.  Otherwise, my output will be lost to the ether, and I don't like doing that. \n", "bold red");
	&usage;
}

our $CONFIG = &get_config($config);

print Dumper($CONFIG) if (($verbose)  and ($verbose > 1));

my $action = $ARGV[0];

given ($action) {
	when (/(?:mounts|fs|filesystems)/) {
		&check_mounts;
	}
	when (/memory/) {
		&check_memory;
	}
	when (/temps/) {
		&check_temps;
	}
	default {
		die colored("Unrecognized action: $action \n", "bold red");
	}
}

###############################################################################
# Subs
###############################################################################
sub usage {
	print <<END;

Usage $0 [-h|--help] [-v|--verbose] [-c|--config] <config file> action

Where:

-h|--help			Displays this useful message, then exits.
-v|--verbose			Prints more verbose output.  Usually used for debugging.
-c|--config			Specifies the config file to use.  Cannot operate without
				a valid YAML config file.

ACTIONS are as follows:

memory				Check the memory and swap for usage data. Emails 
				notification if/when threashold reached.  Thresholds 
				specified in config file.
mounts|fs|filesystems		Check the filesystems for usage data.  Emails
				notification if/when threshold reached.  Thresholds
				specified in config file.

END

	exit 1;			# exit "true" in the absence of a true boolean
}

sub ltrim { my $s = shift(@_); $s =~ s/^\s+//;       return $s; }
sub rtrim { my $s = shift(@_); $s =~ s/\s+$//;       return $s; }
sub  trim { my $s = shift(@_); $s =~ s/^\s+|\s+$//g; return $s; }

sub get_config {
	my $config_file = shift(@_);

	my $config_ref = LoadFile($config_file);
	return $config_ref;
}

sub send_message {
	my $severity = shift(@_);
	my $app = shift(@_);

	my %sev = (
		1	=>	'notice',
		2	=>	'warning',
		3	=>	'critical'
	);

	if ($from_bool{$CONFIG->{'gmail'}}) {
		use Email::Send::SMTP::Gmail;

		my $msg = Email::Send::SMTP::Gmail->new(
			'-smtp'		=>	'gmail.com',
			'-login'	=>	$CONFIG->{'authuser'},
			'-pass'		=>	$CONFIG->{'authpass'},
		);

		$msg->send(
			'-to'		=>	$CONFIG->{'to'},
			'-subject'	=>	ucfirst($sev{$severity}).": ".ucfirst($app),
			'-verbose'	=>	0,
			'-body'		=>	"Your system (".$CONFIG->{'hostname'}.") has reached $sev{$severity} status of $app\.\n",
			'-attachments'	=>	''
		);

		$msg->bye;
	} else {
		MIME::Lite->send('smtp', $CONFIG->{'smtp-server'}, 'Debug'=>$from_bool{$CONFIG->{'smtp-debug'}});
		my $msg = MIME::Lite->new(
			'From'		=>	$CONFIG->{'from'},
			'To'		=>	$CONFIG->{'to'},
			'Cc'		=>	$CONFIG->{'cc'},
			'Subject'	=>	ucfirst($sev{$severity}).": ".ucfirst($app),
			'Data'		=>	"Your system (".$CONFIG->{'hostname'}.") has reached $sev{$severity} status of $app\.\n",
		);

		$msg->send;
	}

	return 1;
}

sub send_notice {
	my $app = shift(@_);
	&send_message(1, $app);

	return 1;
}

sub send_warning {
	my $app = shift(@_);
	&send_message(2, $app);

	return 1;
}

sub send_critical {
	my $app = shift(@_);
	&send_message(3, $app);

	return 1;
}

sub get_binaries {
	$free = `which free`;
	chomp($free);

	if ((!defined($free)) or ($free eq "")) {
		warn colored("Unable to find the `free` utility! \n", "yellow");
		return 0;
	}

	$df = `which df`;
	chomp($df);

	if ((!defined($df)) or ($df eq "")) {
		warn colored("Unable to find the `df` utility! \n", "yellow");
		return 0;
	}

	$sensors = `which sensors`;
	chomp($sensors);

	if ((!defined($sensors)) or ($sensors eq "")) {
		warn colored("Unable to find the `sensors` binary! \n", "yellow");
		return 0;
	}

	return 1;
}

sub check_mounts {
	# check the mounts
	# mail if meet threshold
	print colored("Checking mounts .... ", "bold green");
	open DF, "$df |" or die "There was a problem loading the df utility: $! \n";
	while (my $line = <DF>) {
		chomp($line);
		given ($line) {
			when (/Filesystem\s+/) {
				# skip the header
				next;
			}
			when (/^(?:none|udev|(?:dev)?tmpfs|shm|cgroup_root)/) {
				# don't really care about tmp filesystems
				next;
			}
			when (/(\/dev\/x?(?:[sv]d[a-f]\d|disk\/by-label\/DOROOT|mapper\/opt_crypt|dm\-\d))\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\%\s+(.*)/) {
				my $fs = $1; my $b = $2; my $u = $3; my $av = $4; my $p = $5; my $mnt = $6;
				my $cp = ($av * 100) / $b;
				print colored("Percnt Used: $p\%\tCalc Percnt Free: ".sprintf("%-3.2f%%", $cp)." \n", "bold cyan") if ($verbose);
				if (($cp > 5) and ($cp < 10)) {
					print colored("Sending notice... \n", "bold yellow") if ($verbose);
					given ($action) {
						when (/(?:fs|filesystems)/) {
							print colored(sprintf("$fs: %-3.2f%% free", $cp)." \n", "bold yellow") if ($verbose);
						}
						when (/(?:mounts)/) {
							print colored(sprintf("$mnt: %-3.2f%% free", $cp)." \n", "bold yellow") if ($verbose);
						}
						default { die colored("Unrecognized action: $action \n", "bold red"); }
					}
					&send_notice($action);
					print colored("notice. \n", "bold yellow");
				} elsif (($cp > 1) and ($cp <= 5)) {
					print colored("Sending warning... \n", "yellow") if ($verbose);
					given ($action) {
						when (/(?:fs|filesystems)/) {
							print colored(sprintf("$fs: %-3.2f%% free", $cp)." \n", "yellow") if ($verbose);
						}
						when (/(?:mounts)/) {
							print colored(sprintf("$mnt: %-3.2f%% free", $cp)." \n", "yellow") if ($verbose);
						}
						default { die colored("Unrecognized action: $action \n", "bold red"); }
					}
					&send_warning($action);
					print colored("warning. \n", "yellow");
				} elsif ($cp <= 1) {
					print colored("Sending critical... \n", "bold red") if ($verbose);
					given ($action) {
						when (/(?:fs|filesystems)/) {
							print colored(sprintf("$fs: %-3.2f%% free", $cp)." \n", "bold red") if ($verbose);
						}
						when (/(?:mounts)/) {
							print colored(sprintf("$mnt: %-3.2f%% free", $cp)." \n", "bold red") if ($verbose);
						}
						default { die colored("Unrecognized action: $action \n", "bold red"); }
					}
					&send_critical($action);
					print colored("critical. \n", "bold red");
				} else {
					print colored("Within operational parameters... \n", "green") if ($verbose);
					given ($action) {
						when (/(?:fs|filesystems)/) {
							print colored(sprintf("$fs: %-3.2f%% free", $cp)." \n", "green") if ($verbose);
						}
						when (/(?:mounts)/) {
							print colored(sprintf("$mnt: %-3.2f%% free", $cp)." \n", "green") if ($verbose);
						}
						default { die colored("Unrecognized action: $action \n", "bold red"); }
					}
					print colored("good. \n", "bold green");
				}
			}
			default {
				print "Line didn't match: \n";
				print "$line \n";
			}
		}
	}
	close DF or die "There was a problem closing the df utility: $! \n";

	return 1;
}

sub check_memory {
	# check memory
	# mail if meet threshold
	print colored("Checking memory ..... ", "bold green");
	open FREE, "$free -t |" or die "There was a problem loading the free utility: $! \n";
	while (my $line = <FREE>) {
		chomp($line);
		given ($line) {
			when (/total\s+used\s+free\s+shared\s+buffers\s+cached/) {
				# skip the headers
				next;
			}
			when (/total\s+used\s+free\s+shared\s+buff\/cache\s+available/) {
				# skip the headers
				next;
			}
			when (/\-\/\+ buffers\/cache\:\s+\d+\s+\d+/) {
				# skip the headers
				next;
			}
			when (/Mem:\s+(\d+)\s+(\d+)\s+(\d+).*/) {
				my $t = $1; my $u = $2; my $f = $3;
				my $p = ($f * 100) / $t;
				if (($p > 5) and ($p <= 10)) {
					print colored("Sending notice...\n", "bold yellow") if ($verbose);
					print colored(sprintf("Mem: %-3.2f%% free", $p)." \n", "bold yellow") if ($verbose);
					&send_notice($action);
					print colored("notice. \n", "bold yellow");
				} elsif (($p > 1) and ($p <= 5)) {
					print colored("Sending warning... \n", "yellow") if ($verbose);
					print colored(sprintf("Mem: %-3.2f%% free", $p)." \n", "yellow") if ($verbose);
					&send_warning($action);
					print colored("warning. \n", "yellow");
				} elsif ($p <= 1) {
					print colored("Sending critical.... \n", "bold red") if ($verbose);
					print colored(sprintf("Mem: %-3.2f%% free", $p)." \n", "bold red") if ($verbose);
					&send_critical($action);
					print colored("critical. \n", "bold red");
				} else {
					print colored("Within operational parameters... \n", "green") if ($verbose);
					print colored(sprintf("Mem: %-3.2f%% free", $p)." \n", "green") if ($verbose);
					print colored("good. \n", "bold green");
				}
			}
			when (/Swap:\s+(\d+)\s+(\d+)\s+(\d+).*/) {
				my $t = $1; my $u = $2; my $f = $3;
				next if ($t == 0);
				my $p = ($f * 100) / $t;
				if (($p > 5) and ($p <= 10)) {
					print colored("Sending notice...\n", "bold yellow") if ($verbose);
					print colored(sprintf("Swap: %-3.2f%% free", $p)." \n", "bold yellow") if ($verbose);
					&send_notice($action);
					print colored("notice. \n", "bold yellow");
				} elsif (($p > 1) and ($p <= 5)) {
					print colored("Sending warning... \n", "yellow") if ($verbose);
					print colored(sprintf("Swap: %-3.2f%% free", $p)." \n", "yellow") if ($verbose);
					&send_warning($action);
					print colored("warning. \n", "yellow");
				} elsif ($p <= 1) {
					print colored("Sending critical.... \n", "bold red") if ($verbose);
					print colored(sprintf("Swap: %-3.2f%% free", $p)." \n", "bold red") if ($verbose);
					&send_critical($action);
					print colored("critical. \n", "bold red");
				} else {
					print colored("Within operational parameters... \n", "green") if ($verbose);
					print colored(sprintf("Swap: %-3.2f%% free", $p)." \n", "green") if ($verbose);
					print colored("good. \n", "bold green");
				}
			}
			when (/Total:\s+(\d+)\s+(\d+)\s+(\d+).*/) {
				my $t = $1; my $u = $2; my $f = $3;
				my $p = ($f * 100) / $t;
				if (($p > 5) and ($p <= 10)) {
					print colored("Sending notice...\n", "bold yellow") if ($verbose);
					print colored(sprintf("Total: %-3.2f%% free", $p)." \n", "bold yellow") if ($verbose);
					&send_notice($action);
					print colored("notice. \n", "bold yellow");
				} elsif (($p > 1) and ($p <= 5)) {
					print colored("Sending warning... \n", "yellow") if ($verbose);
					print colored(sprintf("Total: %-3.2f%% free", $p)." \n", "yellow") if ($verbose);
					&send_warning($action);
					print colored("warning. \n", "yellow");
				} elsif ($p <= 1) {
					print colored("Sending critical.... \n", "bold red") if ($verbose);
					print colored(sprintf("Total: %-3.2f%% free", $p)." \n", "bold red") if ($verbose);
					&send_critical($action);
					print colored("critical. \n", "bold red");
				} else {
					print colored("Within operational parameters... \n", "green") if ($verbose);
					print colored(sprintf("Total: %-3.2f%% free", $p)." \n", "green") if ($verbose);
					print colored("good. \n", "bold green");
				}
			}
			default {
				# do nothing;
				print "Line didn't match! \n" if ($verbose);
				print "$line \n" if ($verbose);
			}
		}
	}
	close FREE or die "There was a problem closing the free utility: $! \n";

	return 1;
}

sub check_temps {

	print colored("Checking temps....", "bold green");

	my $sensor_str = `$sensors -u`;
	chomp($sensor_str);

	my @sections = split(/\n\n/m, $sensor_str);
	#print Dumper(\@sections);
	foreach my $sect ( @sections ) {
		my @lines = split(/\n/m, $sect);
		#print Dumper(\@lines);
		foreach my $l ( @lines ) {
			$l = &trim($l);
			my ($circid,$adapter,$node,$sensor,$temp);
			given ($l) {
				when (/([a-z]+\-[a-z]+\-\d+)/) {
					$circid = $1;
					print "Circuit ID: $circid \n" if ($verbose);
				}
				when (/Adapter: (.*)/) {
					$adapter = $1;
					print "Adapter: $adapter \n" if ($verbose);
				}
				when (/((?:temp|Core|Physical id|Exhaust)\s*\d\d?)\:/) {
					$node = $1;
					print "Node: $node \n" if ($verbose);
				}
				when (/(temp\d+\_(?:input|max(?:\_hyst)?|crit(?:\_(?:alarm|hyst))?|emergency(?:\_hyst)?)):\s+(\d+\.\d+)/) {
					$sensor = $1; $temp = $2;
					print "Sensor: $sensor \n" if ($verbose);
					print "Temp: $temp \n" if ($verbose);
				}
				default {
					# if we get here, there is something wrong or unexpected.
					die colored("Unrecognized section line: |$l| \n", "bold red");
				}
			}
			my $sensor_obj = LASObjects::Sensor->new($circid,$adapter,$node,$sensor,$temp);
		}
	}

	return 1;
}
